SESSION_USER_KEY = "user"
SESSION_USER_USERNAME = "u"
SESSION_USER_DISPLAY_NAME = "dn"
SESSION_USER_ROLE = "r"
SESSION_USER_AUTH_METHOD = "am"
SESSION_USER_IAT = "iat"
SESSION_CSRF_FIELD = "csrf_token"
SESSION_CSRF_TOKEN = SESSION_CSRF_FIELD
